[project]
name = "ticketing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Shrisha", email = "shrishasj07@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
ticketing = "ticketing:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
